### ISSUE TITLE
Category mappings

### ISSUE THREAD

**Issue by Sarala26** [rwhalen/bluecoat-sitereview#1]
Where can I get the list of category - number mappings? I want to categorize as a different site.

**Comment by rwhalen** [comment]
You can find them by viewing the HTML on the submission page:

16 Abortion
1 Adult/Mature Content
23 Alcohol
22 Alternative Spirituality/Belief
30 Art/Culture
59 Auctions
84 Audio/Video Clips
32 Brokerage/Trading
21 Business/Economy
29 Charitable Organizations
51 Chat (IM)/SMS
26 Child Pornography
108 Computer/Information Security
97 Content Servers
25 Controlled Substances
103 Dynamic DNS Host
106 E-Card/Invitations
27 Education
52 Email
20 Entertainment
7 Extreme
56 File Storage/Sharing
31 Financial Services
87 For Kids
11 Gambling
33 Games
34 Government/Legal
17 Hacking
37 Health
68 Humor/Jokes
107 Informational
109 Internet Connected Devices
110 Internet Telephony
5 Intimate Apparel/Swimsuit
45 Job Search/Careers
44 Malicious Outbound Data/Botnets
43 Malicious Sources/Malnets
121 Marijuana
112 Media Sharing
35 Military
50 Mixed Content/Potentially Adult
46 News/Media
53 Newsgroups/Forums
96 Non-Viewable/Infrastructure
6 Nudity
85 Office/Business Applications
111 Online Meetings
83 Peer-to-Peer (P2P)
47 Personals/Dating
63 Personal Sites
18 Phishing
118 Piracy/Copyright Concerns
98 Placeholders
36 Political/Social Advocacy
3 Pornography
102 Potentially Unwanted Software
86 Proxy Avoidance
113 Radio/Audio Streams
60 Real Estate
49 Reference
54 Religion
57 Remote Access Tools
64 Restaurants/Dining/Food
9 Scam/Questionable/Illegal
40 Search Engines/Portals
4 Sex Education
93 Sexual Expression
58 Shopping
55 Social Networking
61 Society/Daily Living
71 Software Downloads
101 Spam
65 Sports/Recreation
92 Suspicious
38 Technology/Internet
24 Tobacco
95 Translation
66 Travel
114 TV/Video Streams
67 Vehicles
14 Violence/Hate/Racism
15 Weapons
88 Web Ads/Analytics
89 Web Hosting
90 I Don't Know
